### PR TITLE
Add ALAC Support

### LINKED ISSUE #1: Support for ALAC
Currently only supports PCM data; no ALAC support yet.

For AirSonos users: You can work around this on OS X by selecting the system audio instead of direct output from iTunes or AirFoil. You can do this by alt+clicking the volume icon in the top bar, or going through Sound Output in System Preferences.

OS X Volume Icon:
screen shot 2014-11-25 at 10 21 31 pm

Or via System Preferences:
screen shot 2014-11-25 at 10 21 51 pm

### PR DESCRIPTION
**Pull request by microadam**
Fixes #1 

Big thanks to aspergatus, wa7on and auchenberg for various pointers and their work which helped me track down where the issues were to get this working.

### CODE REVIEW

**Comment by microadam** [comment]
OK, so it looks like this require alot more work (upgrading libalac) to get it working on 0.12 plus, so it could me merged, but will only work on 0.10 for the time being. Hadn't tested it at all on 0.12...

**Comment by kylewelsby** [comment]
I have traced the compatibility issue down to a single file https://github.com/stephank/node-libalac/blob/master/binding.cc as there are [breaking changes between v0.10 to v0.12](https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/). Sadly I do not know enough `C` to upgrade this file.

**Comment by microadam** [comment]
Now working on 0.10, 0.12 and 4.1

**Comment by sodabrew** [comment]
Using this branch as the "nodetunes" dependency for airsonos works great! Thank you @microadam! Hope you will have a moment to review and merge @stephen!

**Comment by stephen** [comment]
Hi all, thanks for the hard work on this. Sorry for the delay - will take a look at getting this merged!

@microadam, @aspergatus - feel free to add yourselves as contributors in `package.json` if you like.

**Comment by stephen** [comment]
Thanks! Released as 0.3.0 (feel free to open a separate PR to add as contributors)

**Comment by vkoi81** [comment]
Thanks @stephen.

**Comment by RealGandy** [comment]
Has this been added to the Windows package yet?
Cheers

**Comment by GeorgeScottow** [comment]
Is it possible to apply this fix with a current Windows package install? Thanks

**Comment by macmatt43** [comment]
I would also be interested in an updates Windows package or maybe some pointers as to how I can create this myself. My initial attempts at tweaking package.json in the existing Windows Pre-Build v0.0.19 did not work. Can you please let me know how to successfully incorporate nodetunes v0.3.0 into this? Many thanks

**Pull request merged**
